//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMasterDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public OrderMaster()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
